### ISSUE TITLE
Thanks for the idea & fork notice

### ISSUE THREAD

**Issue by jppellet** [drendog/Logic-Circuit-Simulator#5]
Hi,

Not an issue per se (feel free to close it!), but I found no contact info for you and I wanted to let you know. I'm in a team that develops teaching material for high-school computer-science courses for Switzerland and I've forked your repo, initially to make the web app easily embeddable in our teaching material. The basic idea got a warm reception and I ended up rewriting it in TypeScript and adding many components (displays, ALU, registers, counters, decoders, RAM/ROM, etc.), to the point where some teachers are now using it to simulate small 4-bit CPUs.

My fork is here: <https://github.com/jppellet/Logic-Circuit-Simulator> and this is the live app: <https://logic.modulo-info.ch>.

Thanks again for the initial code base, which allowed the project to start!

**Comment by drendog** [comment]
Thank you for reaching out and sharing your experience with this project. I'm appreciate your kind words and I'm thrilled to hear that the project has grown and evolved into something that is being used as material to teach. I'm really impressed by the additions and improvements you have made on your fork. It's always exciting to see how open source projects can be taken in new directions and used to solve different problems.

This project was born from my need to simplify the study of logic circuits for a subject of my degree course. So I had an idea how to develop a logic circuit simulator, but at the beginning I was very doubtful if it would ever work. However, I decided to give it a try and realized that the idea was starting to work without major problems. Since the project was taking shape, I decided to make it as user friendly as possible according to my very limited skills, and to publish it so that it could be useful to other students.

Also, if I can be of any help, I'd be happy to contribute to your fork as well. I would also like to point out that the work you have done has been amazing and you have made this project absolutely awesome and masterpiece. I never imagined that this initial code of the project could be taken to this level.

Thanks again for your contribution and best of luck with your teaching material development, future projects and new adventures!
❤️

**Comment by jppellet** [comment]
Thanks a lot for your kind words, too! Although this has been taking may more of my time than I initially imagined, I've been enjoying every second of it. Developing tools useful for the community (whoever that community ends up being) is a great reward.

So, thanks for sharing, for the permissive license, and all the best to you, too!
